# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='key',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prvkey',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pubkey',
            field=models.CharField(max_length=64),
        ),
    ]
